### ISSUE TITLE
Improvements for enabling lorax to build chroots different from OS you run from

### ISSUE THREAD

**Issue by jaymzh** [rhinstaller/lorax#116]
@dcantrell and I just had a long discussion about how to improve this and came up with some relatively simple improvements that I wanted to get written down somewhere before it falls out of my head. At some point I may send the relevant PRs... but I'm not committing to it yet ;)

Problem:
* If you use an older OS to build newer installer media (i.e. run RHEL 7 lorax to build a rawhide installer) you will run into templates that don't match the chroot and it will fail
* If you grab the newer postinst template from github so that the `install` rules match the new packages, then all of the templates will fail later when it tries to install the "config_files" (sshd config, pam config, etc.)
* If you munge the templates for the version of lorax you have, you'll build an installer environment that will not work (lacking the right config files for the version of rawhide used to build the chroot)

Solution:
1. The artifacts in `config_files` are what anaconda needs for it's environment and thus should be stored in the anaconda repo and thus subsequently in the anaconda package
2. Update lorax to have an option to overwrite a template (rather than add a template). Ala. `--postinst-template=...` or possibly `--template-dir`

Once that's done you should in theory be able to cross build easily with any version of lorax and the latest templates from github.

**Comment by cgwalters** [comment]
FWIW I just run lorax from inside a Docker container.

**Comment by jaymzh** [comment]
So we ended up doing this inside `mock` and so this isn't necessary. However, the second point above is near to a thing we do need. I'll close this and make a separate issue.
