### ISSUE TITLE
Difference Package Installation from Kickstart form Lorax template

### ISSUE THREAD

**Issue by kellerkind** [rhinstaller/lorax#120]
For me it is not clear when to use kickstart and when to use lorax template files to install a package or configure a file. E.g. it is not clear which package repos the template files would pull in on installpkg command. Is it relying on anaconda's preparation part? Is /mnt/sysimage mounted when the template magic is done?

Could you shortly answer where to use kickstart and where to use the templates?

I wonder if I could use the gihub lorax version in RHEL 7.2. Which one is currently the last one supported in RHEL?

**Comment by bcl** [comment]
Lorax is used to create the boot.iso, it doesn't use kickstart or anaconda at all. Take a look at https://rhinstaller.github.io/lorax/lorax.html for all the details about templates.

The lorax version for RHEL7 is found in the rhel7-branch. You can use it directly from a git checkout if you pass: PYTHONPATH=./src/ ./src/sbin/lorax
