### ISSUE TITLE
Ensure all content is tracked by metadata

### ISSUE THREAD

**Issue by jeremycline** [rhinstaller/lorax#121]
# Problem Description
I'll start by saying I wasn't sure whether to file this issue against Pungi or Lorax (or some other tool I don't yet know about). If there is nothing to be done in Lorax to fix this problem, I would greatly appreciate getting pointed in the right direction(s) :smile: 

I work on a project called Pulp. One thing Pulp tries to do is mirror yum repositories and installation trees via HTTP. For yum repositories this is fairly straightforward using repodata. However, we've noticed that there are several images and pieces of content that aren't in the ``treeinfo`` file.

It would be great if Lorax ensured every piece of content that makes it into installation trees is described by metadata (presumably in the ``treeinfo`` file).

# Examples
Here are a few examples I've noticed.

## Fedora
Fedora 23's Server variant released repo has an ``EFI/`` and ``isolinux/`` directory. None of the files in either of those directories are present in the ``treeinfo`` metadata or any other metadata as far as I can tell, so Pulp isn't able to discover them short of guessing filenames.

Fedora 24's Server variant beta repo looks to be missing both the directories Fedora 23 does, but it's also missing the images/efiboot.img and images/macboot.img.

## CentOS

In addition to the files missing in Fedora, CentOS also has GPG keys, the GPL, a EULA, and a text file with the build tag in its tree. I'm not certain when this gets added, so maybe there's nothing to be done in Lorax for this.

## RHEL

RHEL is similiar to CentOS, but it _also_ contains release notes. Again, I don't know that Lorax is responsible for these files.

**Comment by jeremycline** [comment]
I've been told that the GPL and EULA at least are added by Pungi, so I've filed https://pagure.io/pungi/issue/295 as well.

**Comment by bcl** [comment]
Some of it comes from lorax, and others are added by pungi. It does look like lorax isn't adding information for all the images it installs. Could you open a bug for this at https://bugzilla.redhat.com, that's how I prefer to track bugs.

**Comment by jeremycline** [comment]
Thanks for the quick response. I've filed this as https://bugzilla.redhat.com/show_bug.cgi?id=1335160.
