### ISSUE TITLE
Update the x86 templates

### ISSUE THREAD

**Issue by cjschroeder** [rhinstaller/lorax#13]
If the generic-logos package is installed, rather than fedora-logos, livemedia-creator "--make-iso" fails when building "boot.iso".

Python traceback:
**IOError: nothing matching /var/tmp/tmpPtUQ_u/usr/share/anaconda/boot/syslinux-splash.png in /**

This is due to each package installing the "syslinux-splash.png" file in different locations:

generic-logos: **/usr/share/anaconda/pixmaps/syslinux-splash.png**
fedora-logos: **/usr/share/anaconda/boot/syslinux-splash.png**

Update to install the generic-logos file, if it exists; else, default.

```diff
diff --git a/share/live/x86.tmpl b/share/live/x86.tmpl
index f60b80d..dbd61bf 100644
--- a/share/live/x86.tmpl
+++ b/share/live/x86.tmpl
@@ -29,7 +29,11 @@ install ${SYSLINUXDIR}/libutil.c32 ${BOOTDIR}
 install ${configdir}/isolinux.cfg ${BOOTDIR}
 install ${configdir}/boot.msg ${BOOTDIR}
 install ${configdir}/grub.conf ${BOOTDIR}
-install usr/share/anaconda/boot/syslinux-splash.png ${BOOTDIR}/splash.png
+%if exists("usr/share/anaconda/pixmaps/syslinux-splash.png"):
+   install /usr/share/anaconda/pixmaps/syslinux-splash.png ${BOOTDIR}/splash.png
+%else:
+   install usr/share/anaconda/boot/syslinux-splash.png ${BOOTDIR}/splash.png
+%endif
 install boot/memtest* ${BOOTDIR}/memtest
 
 ## configure bootloader
diff --git a/share/x86.tmpl b/share/x86.tmpl
index 7273e28..3f1e470 100644
--- a/share/x86.tmpl
+++ b/share/x86.tmpl
@@ -29,7 +29,11 @@ install ${SYSLINUXDIR}/libutil.c32 ${BOOTDIR}
 install ${configdir}/isolinux.cfg ${BOOTDIR}
 install ${configdir}/boot.msg ${BOOTDIR}
 install ${configdir}/grub.conf ${BOOTDIR}
-install usr/share/anaconda/boot/syslinux-splash.png ${BOOTDIR}/splash.png
+%if exists("usr/share/anaconda/pixmaps/syslinux-splash.png"):
+   install /usr/share/anaconda/pixmaps/syslinux-splash.png ${BOOTDIR}/splash.png
+%else:
+   install usr/share/anaconda/boot/syslinux-splash.png ${BOOTDIR}/splash.png
+%endif
 install boot/memtest* ${BOOTDIR}/memtest
 
 ## configure bootloader
```

**Comment by bcl** [comment]
An alternative would be for generic-logos to put the splash in the right place. It shouldn't be installed at the same time as fedora-logos so there wouldn't be a conflict.

**Comment by cjschroeder** [comment]
They are two different packages with their own unique %{_datarootdir}'s.  The two packages conflict and would never coexist.

**Comment by bcl** [comment]
Yeah, after looking at fedora-logos and generic-logos it looks like generic has fallen behind a bit. It needs to be updated to be closer to fedora-logos. Please open a bug with generic-logos at https://bugzilla.redhat.com/
