### ISSUE TITLE
drivers/target are necessary to support installation over ISERT/SRPT

### ISSUE THREAD

**Issue by HonggangLI** [rhinstaller/lorax#133]
share/templates.d/99-generic/runtime-cleanup.tmpl

 90 ## clean up kernel modules
 91 removekmod sound drivers/media drivers/hwmon \
 92            net/atm net/bluetooth net/sched net/sctp \
 93            net/rds net/l2tp net/decnet net/netfilter net/ipv4 net/ipv6 \
 94            drivers/watchdog drivers/target drivers/rtc drivers/input/joystick \
 95            drivers/bluetooth drivers/edac drivers/staging \
 96            drivers/usb/serial drivers/usb/host drivers/usb/misc \
 97            fs/ocfs2 fs/ceph fs/nfsd fs/ubifs fs/nilfs2 \
 98            arch/x86/kvm

As modules, ib_srpt and ib_isert, depends on target modules, so please do not remove drivers/target. We need them to support installation over RDMA targets, such as SRP and ISER.

thanks

**Comment by bcl** [comment]
Could you open a bug for this at https://bugzilla.redhat.com ? Thanks.

**Comment by HonggangLI** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1348381
