### ISSUE TITLE
runtime-cleanup.tmpl removes sshd-keygen, breaks sshd

### ISSUE THREAD

**Issue by bwann** [rhinstaller/lorax#153]
In 99-generic cleanup template there's a rule to remove ```/usr/libexec/*```, which removes ```/usr/libexec/openssh/sshd-keygen```.

When booting a Lorax-generated Anaconda rawhide image with 'inst.sshd' on the kernel command line to start sshd, sshd is started via systemd but there are no host keys so client connections are refused.

```
lorax.log:2016-08-18 18:42:37,696 DEBUG pylorax.ltmpl:
  removed /var/tmp/lorax.j_ttxdrd/installtree//usr/libexec/openssh/sshd-keygen
```

```
Aug 23 23:09:23 localhost systemd[1927]: sshd-keygen@ecdsa.service: Failed at step EXEC spawning /usr/libexec/openssh/sshd-keygen: No such file or directory
Aug 23 23:09:23 localhost systemd[1944]: sshd-keygen@ed25519.service: Failed at step EXEC spawning /usr/libexec/openssh/sshd-keygen: No such file or directory
Aug 23 23:09:23 localhost audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=sshd-keygen@ecdsa comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Aug 23 23:09:23 localhost systemd[1]: sshd-keygen@ed25519.service: Unit entered failed state.
Aug 23 23:09:23 localhost systemd[1]: sshd-keygen@ed25519.service: Failed with result 'exit-code'.

[repeat for sshd-keygen@rsa.service too]

$ ssh root@sparefullhaystack2069.prn1
Connection closed by 2401:db00:172::face:0:1d:0
```

Running something like ```ssh-keygen -f /etc/ssh/ssh_host_rsa_key -N '' -t rsa```  (which is in /bin) from tmux console or a pre-script repairs it and SSH is usable again.

**Comment by jaymzh** [comment]
I can't see any reason to remove `/usr/libexec/*` at all from openssh, openssh-clients, and openssh-server.... we should nuke all of those.

Also, why do we remove `/usr/bin/ssh-*` - that's a terrible idea as well.

**Comment by bcl** [comment]
I think this is the same as https://bugzilla.redhat.com/show_bug.cgi?id=1331753

**Comment by jaymzh** [comment]
@bcl  that bug seems backwards. Why should anaconda be stripping stuff out of the openssh package?

**Comment by jaymzh** [comment]
(I'm not asking to be sarcastic... I was gonna send a PR to nuke those lines, but clearly there's a goal/motivation here I don't understand, so I'm trying to understand it).

**Comment by Jakuje** [comment]
At the moment, I see that you are removing a lot of files files using [this file](https://github.com/rhinstaller/lorax/blob/master/share/templates.d/99-generic/runtime-cleanup.tmpl) (probably to save some space):
```
$ rpm -ql openssh | grep /etc/ssh
/etc/ssh
/etc/ssh/moduli
$ rpm -ql openssh | grep libexec
/usr/libexec/openssh
/usr/libexec/openssh/ssh-keysign
$ rpm -ql openssh-client | grep /usr/bin/ssh-
/usr/bin/ssh-add
/usr/bin/ssh-agent
/usr/bin/ssh-copy-id
/usr/bin/ssh-keyscan
$ rpm -ql openssh-client | grep /usr/bin/slogin
/usr/bin/slogin
$ rpm -ql openssh-clients | grep libexec
/usr/libexec/openssh/ssh-pkcs11-helper
$ rpm -ql openssh-clients | grep /etc/ssh
/etc/ssh/ssh_config
/etc/ssh/ssh_config.d
/etc/ssh/ssh_config.d/05-redhat.conf
$ rpm -ql openssh-server | grep libexec
/usr/libexec/openssh/sftp-server
/usr/libexec/openssh/sshd-keygen
$ rpm -ql openssh-server | grep /etc/ssh
/etc/ssh/sshd_config
```
Basically only `sshd-keygen` and `sshd_config` are crucial to start `sshd` with default configuration. Removing `moduli` is also not a good idea (falling back to the default list of hardcoded primes).

[`slogin` is also gone in F25](https://fedoraproject.org/wiki/Changes/Remove_slogin_and_sshd-keygen) so there is no need to remove it now.

I am also not satisfied with overwriting the default configuration files with [your own](https://github.com/rhinstaller/lorax/blob/master/share/templates.d/99-generic/config_files/common/sshd_config.anaconda). You enable `ChallengeResponseAuthentication` which is disabled in our shipped configuration. Also we plan to use the configuration files for [System-wide Crypto Policy](https://fedoraproject.org/wiki/Changes/CryptoPolicy), which would get overwritten by your scripts.

As a minimal solution, I would recommend not to remove `/usr/libexec/openssh/sshd-keygen` (remove `/usr/libexec/openssh/sftp-server` if you wish) to resolve this issue. Further, we could see what would be other useful files and why wouldn't you need them.

**Comment by Jakuje** [comment]
See the pull request #160
