### ISSUE TITLE
Is it possible to affect the boot loader config?

### ISSUE THREAD

**Issue by jflorian** [rhinstaller/lorax#168]
With livecd-tools, I was able to customize the bootloader command line to do things like:
- set the boot timeout to 1s -- the default 60s is not usable for embedded OS uses
- set kernel vars, e.g.: `console=ttyS0,115200 console=tty0 usbcore.autosuspend=-1 biosdevname=0 net.ifnames=0 8250.nr_uarts=16`
- enable systemd debugging

So far my luck with livemedia-creator has been that pretty much anything I throw at the `bootloader` directive in the kickstart seems to be ignored.

If this is not possible at present, how hard would it be to develop and where would I need to start?

**Comment by jflorian** [comment]
I've made some progress on this.  It appears that the only way to influence the bootloader of a Live OS image generated with livemedia-creator is to ignore the `bootloader` directive in the kickstart and to instead focus on hacking the Mako templates, e.g., `lorax/share/templates.d/99-generic/live/x86.tmpl` where the line `replace @ROOT@`... appears.  As I explore these templates I'm seeing some incredibly powerful features here.

So now that I've had some basic success affecting the bootloader when creating my image by running lm-c directly, the next issue I face is **how do I tell my Koji system that a livemedia task is to use custom templates?**  Is that yet possible or does Koji need to be extended to allow this?

**Comment by bcl** [comment]
That's correct, the bootloader kickstart command controls Anaconda, not the final iso image. If you were building just a disk image you'd be fine, but the iso is another step applied after Anaconda. You'll have to direct Koji questions to the Koji folks, I don't use it at all myself.
