### ISSUE TITLE
Transfer some requires from blivet to lorax

### ISSUE THREAD

**Issue by mulkieran** [rhinstaller/lorax#17]
Blivet will be losing libblockdev-plugins-all and dosfstools requires. I believe that lorax will need to add a libblockdev-plugins-all requires when this blivet change goes through.

**Comment by bcl** [comment]
That will work for boot.iso creation, but live image creation depends on either the package dependencies or the live spin kickstart contents.
I think it would be better to move them to anaconda, it is using blivet, it knows what capabilities it wants to support, so it should be the right place to require optional packages.

**Comment by mulkieran** [comment]
ok.
