### ISSUE TITLE
when printing out packages being installed print the n-v-r.a not n.a

### ISSUE THREAD

**Issue by ausil** [rhinstaller/lorax#180]
something changed in rawhide recently that has caused lorax to start to be unable to complete.

the error is 
2017-01-29 07:38:48,191: /usr/bin/perl, needed by /var/tmp/lorax.vbio_v1v/installtree/usr/bin/rxe_cfg, does not exist
/usr/bin/perl, needed by /var/tmp/lorax.vbio_v1v/installtree/usr/bin/rxe_cfg, does not exist

the package set has gone from 730 to 733 packages, however I can not see the versions that changed to find out which one of them changed and started pulling in more.

**Comment by bcl** [comment]
What's the environment it is running in? On F25 I'm seeing different errors, sooner. DNF or py3.5 appear to have changed enough to break setting up the repos.

**Comment by bcl** [comment]
@ausil I've pushed changes to master and f25-branch (f25 also didn't have the libhistory change).  I'm not seeing the error you are so it may have been a transient repo problem. But now it should be printing full NEVRA:

`2017-01-30 10:04:06,130: (731/735) iwl100-firmware-39.31.5.1-69.fc26.noarch`

Give it a try if you can and I'll do a new build if there are no other problems.

**Comment by ausil** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1404043 is what broke things. Took a lot of digging to figure it out

On 30 January 2017 7:14:52 pm GMT+01:00, "Brian C. Lane" <notifications@github.com> wrote:
>@ausil I've pushed changes to master and f25-branch (f25 also didn't
>have the libhistory change).  I'm not seeing the error you are so it
>may have been a transient repo problem. But now it should be printing
>full NEVRA:
>
>`2017-01-30 10:04:06,130: (731/735)
>iwl100-firmware-39.31.5.1-69.fc26.noarch`
>
>Give it a try if you can and I'll do a new build if there are no other
>problems.
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/rhinstaller/lorax/issues/180#issuecomment-276143725

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
