### ISSUE TITLE
SQL Injection..?

### ISSUE THREAD

**Issue by Frodox** [rhinstaller/lorax#183]
Same as in F25 I'm trying to generate installed packages list for anaconda-env for `rhel7-branch`.

I hacked `runtime-postinstall.tmpl` in a way:
```
runcmd chroot ${root} /bin/rpm -qa --qf '%{NAME},%{NVRA}\n' --pipe "sort | tee /root/lorax-packages-formatted.log"
```

but I get empty log `/root/lorax-packages-formatted.log` and this msgs in lorax log:
```
2017-02-04 00:07:22,268 DEBUG pylorax.ltmpl: template line 68: runcmd chroot /var/tmp/lorax.fdP_n3/installtree /bin/rpm -qa --qf %NAME,%NVRA\n --pipe sort | tee /root/lorax-packages-formatted.log
2017-02-04 00:07:22,268 DEBUG pylorax.ltmpl: running command: ('chroot', '/var/tmp/lorax.fdP_n3/installtree', '/bin/rpm', '-qa', '--qf', '%NAME,%NVRA\\n', '--pipe', 'sort | tee /root/lorax-packages-formatted.log')
2017-02-04 00:07:22,587 DEBUG pylorax.ltmpl: command finished successfully
```
see - no command output. And in `program.log`:
```
Running... chroot /var/tmp/lorax.fdP_n3/installtree /bin/rpm -qa --qf %NAME,%NVRA\n --pipe sort | tee /root/lorax-packages-formatted.log
error: incorrect format: invalid field width
error: incorrect format: invalid field width
error: incorrect format: invalid field width
...
```

And with this format all fine:
```
runcmd chroot ${root} /bin/rpm -qa --qf '%{NAME} %{NVRA}\n' --pipe "sort | tee /root/lorax-packages.log"
```

in console (manually) both works fine. Other delimeters (`;` `-`) works fine too. Looks like `runcmd` could handle `,` in args correctly...

**Comment by bcl** [comment]
I'm not sure what you mean by the title, no SQL is involved here.

The arguments eventually make their way into subprocess.Popen with no obvious changes that would split out the comma. Also note that this isn't a bash shell, it uses Python's subprocess.Popen so things may work differently than they do from a cmdline.

**Comment by Frodox** [comment]
> I'm not sure what you mean by the title, no SQL is involved here.

Well, no sql obviously. Just some incorrect handling. There are [no any restrictions in docs](https://rhinstaller.github.io/lorax/pylorax.html?highlight=runcmd#pylorax.ltmpl.LoraxTemplateRunner.runcmd), and resulting line looks like correct one
```
('chroot', '/var/tmp/lorax.fdP_n3/installtree', '/bin/rpm', '-qa', '--qf', '%NAME,%NVRA\\n', '--pipe', 'sort | tee /root/lorax-packages-formatted.log')
```
but someone in the middle break it by commas. Looks like a bug for me.
