### ISSUE TITLE
boot.iso should have supported bit if created with --isfinal

### ISSUE THREAD

**Issue by lubomir** [rhinstaller/lorax#186]
When lorax is run with the `--isfinal` option, I think lorax should add `--supported-iso` to its invocation of `implantisomd5`.

Currently when you check the iso it always claims to be unsupported:

```
$ checkisomd5 --md5sumonly boot.iso
boot.iso:   68f71e883070f611e0862e57eb6eb0dc
Fragment sums: e2f7bf8efd4721aa28887f97b7c6deb64807a6a4b3c6a4da6e35e381ffad
Fragment count: 20
Supported ISO: no
```

I'm not completely sure this would be correct, but at least Pungi expects this should happen when calling lorax.

**Comment by bcl** [comment]
I'd never noticed that option before. According to the docs it makes anaconda skip the media check, which is no longer true (and wouldn't be a good idea anyway), so I'm not sure what benefit this would have.

**Comment by lubomir** [comment]
Good point. If anaconda no longer looks at the bit, then it indeed does not make much sense to add it there. Thanks for the info.
