### ISSUE TITLE
Impossible to install several kernel on a live iso install

### ISSUE THREAD

**Issue by ycollet** [rhinstaller/lorax#195]
Hello,

I try to build an iso file using livemedia-creator.
I wanted to add a standard kernel and a realtime kernel from CCRMA repo.
The iso is correctly generated, but the realtime kernel doesn't appears in the boot menu.
As far as I understand, lorax install only the standard kernel and ignore the rt one.
I tried to use x86.tmpl but the iso generation failed because of the arguments of mkisofs ...

Best regards,

YC

**Comment by bcl** [comment]
See #196
