### ISSUE TITLE
livemedia-creator lacks a way to add files to the iso image

### ISSUE THREAD

**Issue by lesnake** [rhinstaller/lorax#197]
When livemedia-creator exits, the result is an iso image contains squashfs, which contains ext3f, which is the rootfs.
The kickstart allows installing packages, and do post processing in the rootfs. But not in the iso.

.ks files available in /usr/share/doc/lorax/fedora-livemedia.ks contains this %post section :

> %post`
>
 >--nochroot
>cp $INSTALL_ROOT/usr/share/licenses/*-release/* **$LIVE_ROOT**/
>
>\# only works on x86, x86_64
>if [ "$(uname -i)" = "i386" -o "$(uname -i)" = "x86_64" ]; then
>  if [ ! -d $LIVE_ROOT/LiveOS ]; then mkdir -p **$LIVE_ROOT**/LiveOS ; fi
>  cp /usr/bin/livecd-iso-to-disk **$LIVE_ROOT**/LiveOS
>fi
>%end

Which does not work : 
- no licences files in the iso root
- no livecd-iso-to-disk in /LiveOS of the iso

Instead:
- licence files are in the mock root
- the LiveOS folder is created in the mock root

livecd-creator mechanism based on %post using $LIVE_ROOT has no equivalent, which is, for me, a lack in the said .ks file compatibility.

Having the possibility to interact with the iso file before its packing could be great to :
- add some files (documents, manuals, MS windows stuff)
- add some more grub menu entries

**Comment by havealoha** [comment]
A recent patch https://github.com/rhinstaller/lorax/commit/c91278a17d34b92d3bd549b5ff862e7375c21975 accomplishes this by modifying share/templates.d/99-generic/live/x86.tmpl . Here BCL is using this to copy a license file to iso /. You could add your own template using this method.

**Comment by lesnake** [comment]
If I undestand correctely, I have to 
- create my own version of lorax x86.tmpl, say, myown_x86.tmpl
- copy my files in the section
\# install bootloader and config files
with something like
install  LIVE_ROOT/* ${BOOTDIR}
- use livemedia-creator [stuff] --lorax-templates myown_x86.tmpl

Correct ?

**Comment by havealoha** [comment]
No, i think, either append your file names to $f or add them to the end mkisofs after copying them to $LIVEDIR. Modify lorax x86.tmpl directly or copy all templates to new dir and modify x86 because  --lorax-templates uses a directory

**Comment by lesnake** [comment]
Ok. I get the workflow now.

I think I am going to stick to my actual workflow : a basic mount of the iso, then a copy in a writable location, do my patch/copy job then repack the iso.

For this workflow I think the best could be the calling of a script given by the user as a LMC parameter with the outroot, current path as arguments & environment.

**Comment by bcl** [comment]
You can do this with `--add-arch-template` added in commit 67217f56425ce24e74f0a75010b22f5c462de239 which also added including content from iso-graft in the workdir.

**Comment by frafra** [comment]
I think it should be documented that `%post --nochroot` is no more working.
I tried to create an `iso-graft` directory inside the working directory the right way to add arbitrary content, but the content has not been included. Am I missing something?

**Comment by alexbozhenko** [comment]
Hello. I have similar question.
I am using lorax to build live image like this:
`livemedia-creator --vcpus 4  --resultdir lorax-output --make-pxe-live --iso CentOS-7-x86_64-Minimal-1708.iso --ks ks2.cfg --vnc vnc=127.0.0.1:5`
Is there a way to inject files to the resulting squashfs image using lorax?
@bcl Brian, could you please comment on this?

**Comment by alcir** [comment]
So you confirm that ```%post --nochroot``` doesn't work?

**Comment by saifeiLee** [comment]
> You can do this with `--add-arch-template` added in commit [67217f5](https://github.com/weldr/lorax/commit/67217f56425ce24e74f0a75010b22f5c462de239) which also added including content from iso-graft in the workdir.

Same question here. Have not found a solution. I just want to add files to the ISO /. Any question please?

**Comment by saifeiLee** [comment]
> So you confirm that `%post --nochroot` doesn't work?

I tried, did not work.

**Comment by squirrlien** [comment]
Solution is here.. https://pagure.io/fedora-kickstarts/c/1c9fefa1865ced5b357b3ec5f3b7d5bd856809fc

"Adapt for livemedia-creator changes
    
    Now that F24 images are made with livemedia-creator instead of
    livecd-creator, the kickstart parser has changed; the new kickstart
    parser doesn't understand the $INSTALL_ROOT variable we'd been using in
    %post --nochroot scripts. This commit fixes this by replacing
    $INSTALL_ROOT usage with hardcoded /mnt/sysimage as docs suggest.
    
    While at this, this commit also fixes a case where resolv.conf would be
    incorrectly copied if it is a symlink, thanks to dgilmore for pointing
    this out."

**Comment by squirrlien** [comment]
Regarding share/templates.d/99-generic/live/x86.tmpl would be great if you could share how you picked up the files/folders you are copying. In my case it wasn't able to get out of the context of the virtual FS to bring anything over from outside. Even when used with the outroot/
