### ISSUE TITLE
Is lm-c or lorax responsible for the funny business with /var/cache/man

### ISSUE THREAD

**Issue by jflorian** [rhinstaller/lorax#201]
I've been trying to figure out why 'man -k bla' doesn't work in my live images.  I initially followed the fedora templates by calling `mandb` in %post but that didn't help.  In debugging this I also added to %post things like `find /var/cache/man -type f` and found that the DB files do exist at that time, but they're gone once I actually go to run my image.  I just took the same kickstart and bypassed lm-c and lorax, essentially doing a standard kickstart install and found the DB files present in that case.  I grepped for `var`, `cache`, `man` in the lorax templates but found no smoking gun.  I can keep digging further, but thought "those in the know" might be able to save me a whole lot of effort since I run lm-c via koji.  I guess my next step would be to run lm-c outside of koji for another data point.

**Comment by bcl** [comment]
Running lmc should be really close to running anaconda on a vm with the same kickstart (that's why it was written). There isn't anything specific to mandb in the code so I don't have anything to add, sorry.
