### ISSUE TITLE
repo with user/pass

### ISSUE THREAD

**Issue by pkking** [rhinstaller/lorax#203]
Hi, i have a repo with username/password, is there a way for lorax to access it ?

**Comment by Frodox** [comment]
I think, in case of new one lorax (which accepts yum-conf), it is possible to specify just as yum/http
` baseurl=http://user:password@www.example.com/repo/`

**Comment by bcl** [comment]
You should be able to do the same from the cmdline, the -s value is passed directly to DNF.

**Comment by pkking** [comment]
Thx @Frodox  @bcl, that's work for me.
