### ISSUE TITLE
Creating an ISO affects the main system

### ISSUE THREAD

**Issue by frafra** [rhinstaller/lorax#206]
The keyboard layout changes when I try to generate an ISO with a different default keyboard layout. This happens even when using `mock`.

**Comment by bcl** [comment]
I need more details. lorax or livemedia-creator? libvirt install or running anaconda on the host (eg. livemedia-creator --no-virt). Version of lorax, etc. and cmdline you are using. Logs may also be helpful, posting them is easier at https://bugzilla.redhat.com (component is lorax) than with github issues.

**Comment by frafra** [comment]
Thank you for your reply. I am using livemedia-creator with anaconda, F25 x86_64. I will report it on bugzilla if it's better.
