### ISSUE TITLE
Package included even if deleted

### ISSUE THREAD

**Issue by frafra** [rhinstaller/lorax#210]
`livecd-creator` fails if the kickstart file explicitly ask for not using a specific package and some dependency is not satisfied, while `livemedia-creator` just ignore the request and add it.
This is clearly visible with the `realmd` package: you can find it in F25 XFCE, even if there not should be, according to https://pagure.io/fedora-kickstarts/blob/f25/f/fedora-xfce-packages.ks#_41

**Comment by bcl** [comment]
lmc doesn't have anything to do with handling package selection. That's all Anacond and DNF. Depending on what is requiring it, you many not be able to exclude it.

**Comment by frafra** [comment]
Ok, thanks. It would be nice to write differences between lmc and livecd-creator (like yum vs dnf), because I suspect that many people, including the Fedora devs who wrote the XFCE ks, expect that the kickstart format is interpreted in the same way.

**Comment by bcl** [comment]
livemedia-creator uses Anaconda, so it's exactly like a normal system installation.
