### ISSUE TITLE
livemedia-creator 25.19 --novirt --make-pxe-live --ks fedora-livemedia.ks not respecting %packages -@libreoffice or -libreoffice*

### ISSUE THREAD

**Issue by havealoha** [rhinstaller/lorax#225]
I dont want libreoffice. livemedia-creator using the default fedora-livemedia.ks is not respecting the -@libreoffice or -libreoffice* in %packages.

I dont want to sort out and list all the packages to include in %packages, I just want to remove libreoffice.

Why does it insist on installing? Ive grepped the logs and cant find any clues. Ive looked in the other packages and cant find it as a dependency.

Is there --exclude support in lorax?:
```
* Thu Jan 12 2012 Martin Gracik <mgracik@redhat.com> 17.2-1
  - lorax: Add option to exclude packages (bcl)
```
What about a way to ad an exclude section to the dnf.conf, yum.conf or the .repo's from within the kickstart using %pre --nochroot??

**Comment by bcl** [comment]
This isn't a lorax/livemedia-creator issue. It's anaconda or package dependencies. If you remove the libreoffice line from the kickstart it shouldn't get installed.

**Comment by havealoha** [comment]
Looks like it was a dependency of unoconf which is in@workstation-product. What has precedence, a dependency or a "-" directive? Removing @libreoffice from %packages does not remove libreoffice. unoconv depends on libreoffice-filters and libreoffice-pyuno which depend on libreoffice*.

**Comment by bcl** [comment]
If something else requires it, it is going to get installed. Probably better to start with something other than @workstation-product then.
