### ISSUE TITLE
Test /api/v0/recipes/diff/<recipe_name>/<from_commit>/<to_commit> fails

### ISSUE THREAD

**Issue by martinpitt** [rhinstaller/lorax#292]
When running tests in a Fedora 27 mock, there is one failure (after fixing some others in #291):
```
======================================================================
FAIL: Test /api/v0/recipes/diff/<recipe_name>/<from_commit>/<to_commit>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/martin/upstream/lorax/tests/pylorax/test_server.py", line 332, in test_13_recipes_diff
    self.assertEqual(data, {"diff": [{"new": {"Version": "0.0.1"}, "old": {"Version": "0.2.1"}}]})
AssertionError: {u'diff': [{u'new': {u'Version': u'0.2.1'}, u'old': {u'Version': u'0.0.1'}}]} != {'diff': [{'new': {'Version': '0.0.1'}, 'old': {'Version': '0.2.1'}}]}
- {u'diff': [{u'new': {u'Version': u'0.2.1'}, u'old': {u'Version': u'0.0.1'}}]}
?  -          -        -           -   ^      -        -           -   ^

+ {'diff': [{'new': {'Version': '0.0.1'}, 'old': {'Version': '0.2.1'}}]}
?                                  ^                            ^
```
I. e. aside from the `u""` unicode prefix noise (which doesn't matter for comparison) the old and new versions are swapped. Is that something specific on my system, or does it fail for you as well?

**Comment by bcl** [comment]
I'm going to bet that this is a libgit problem I ran into, and thought I had solved. If you drop this into test_13_recipes_diff after it sets changes:
    self.assertEqual(changes, None)
And look at the order of the results. The first entry should be the reverted recipe.
I thought this was fixed with commit d2fe65c80cf8a1830bf5784080cd2cd7704bb2a2
For now I think it can be ignored since you should be running it on CentOS7 not Fedora.

**Comment by bcl** [comment]
Ran into this with bdcs-api as well, the fix there was to change the sort mode to Reverse (without Time).

**Comment by bcl** [comment]
Closing this since tests are now passing consistently.
