### ISSUE TITLE
lorax-composer cannot write its own git tree

### ISSUE THREAD

**Issue by martinpitt** [rhinstaller/lorax#319]
With latest lorax-composer creating and deleting recipes fails now:

```
2018-02-09 14:52:32,972: (v0_recipes_new) ggit-error: Failed to create temporary file '/recipes/git/objects/tmp_object_git2_uLs0mq': Permission denied (-1)

[root@594b4069006e /]# ls -l /recipes/
drwxr-xr-x 1 root root 82 Feb  9 14:30 git

# rpm -qa|grep lorax
lorax-19.7.7-1.el7.centos.x86_64
lorax-composer-19.7.7-1.el7.centos.x86_64
```

This started from a completely blank /recipes directory (which is a docker volume, and docker just created it from scratch). It seems the entire git tree is initialized from the process that runs as  root, but being used by the process that runs as user weldr?

Before that I still had a "foo" recipe in that volume, and deletion has the same problem:
```
❱❱❱ curl --unix-socket /run/weldr/weldr/api.socket http://localhost/api/v0/recipes/list
{
  "limit": 20, 
  "offset": 0, 
  "recipes": [
    "foo"
  ], 
  "total": 1
}

{
  "error": {
    "msg": "ggit-error: Failed to create temporary file '/recipes/git/objects/tmp_object_git2_iax2WE': Permission denied (-1)"
  }, 
  "status": false
}
```

and lorax-composer showed a similiar EPERM message.

**Comment by bcl** [comment]
Fixed in lorax-19.7.8-1, also see https://github.com/weldr/ansible-centos7-composer for installation instructions, ends up you can't run anaconda inside docker.
