### ISSUE TITLE
dnf conflict for logos packages during lorax run

### ISSUE THREAD

**Issue by dustymabe** [rhinstaller/lorax#332]
`lorax-28.6-1.fc29.x86_64`

https://github.com/rhinstaller/lorax/pull/327 seems to have made is so that lorax now will add both `fedora-logos` and `generic-logos` to the transaction. Those two packages conflict so we end up with a failure: 

```
DEBUG util.py:439:  dnf.exceptions.DepsolveError: 
DEBUG util.py:439:   Problem: package generic-logos-18.0.0-5.fc28.noarch conflicts with fedora-logos provided by fedora-logos-28.0.2-3.fc28.x86_64
DEBUG util.py:439:    - conflicting requests
```

This seems to be related to https://github.com/rhinstaller/lorax/blob/master/src/pylorax/ltmpl.py#L566-L579. If I add a `logger.info(pkgnvrs)` at line 580 I can see `['fedora-logos-28.0.2-3.fc28', 'generic-logos-18.0.0-5.fc28']` in the output. i.e. it selects **BOTH** packages to install.

**Comment by dustymabe** [comment]
I guess I don't really understand why we are doing special handling of packages (i.e. find package NVRS and pass them directly to dnf) rather than just sending dnf one large group of requires and having it figure out what all to install.

**Comment by bcl** [comment]
Yeah, I'm trying to sort this out now. Not really sure what's going on yet.

The NEVRA change was supposed to allow pinning of versions, but it has a problem when an updates repo is included. That doesn't seem to be related to this logos problem though. Something in the package deps is pulling in both generic-logos and fedora-logos.

**Comment by dustymabe** [comment]
> Something in the package deps is pulling in both generic-logos and fedora-logos.

Is that true, though? From the description I tried to show that both of them get added by the single *request* for `system-logos`.

**Comment by bcl** [comment]
DNF makes the decision what to pull in. When asked for the best latest it is returning 3 things for my test:
Installing [<hawkey.Package object id 7573, fedora-logos-26.0.1-3.fc27.x86_64, lorax-repo-0>, <hawkey.Package object id 9165, generic-logos-18.0.0-4.fc27.noarch, lorax-repo-0>, <hawkey.Package object id 56821, fedora-logos-28.0.2-1.fc27.x86_64, lorax-repo-1>] for system-logos

fedora-logos has already been selected before running runtime-install.tmpl so it should be the only thing it returns (and it should be the latest version, from the updates repo)

**Comment by dustymabe** [comment]
> When asked for the best latest it is returning 3 things for my test

Is that a bug?

**Comment by dustymabe** [comment]
I can reproduce this with `installpkg /usr/bin/curl` as well. 

```
2018-02-23 17:46:35,620 DEBUG pylorax.ltmpl: ['curl-7.58.0-7.fc28', 'curl-minimal-7.58.0-7.fc28']
...
2018-02-23 17:46:35,836 DEBUG pylorax.ltmpl:   dnf.exceptions.DepsolveError:
2018-02-23 17:46:35,836 DEBUG pylorax.ltmpl:    Problem: package curl-minimal-7.58.0-7.fc28.x86_64 conflicts with curl provided by curl-7.58.0-7.fc28.x86_64
2018-02-23 17:46:35,836 DEBUG pylorax.ltmpl:     - conflicting requests

```


[lorax.log](https://github.com/rhinstaller/lorax/files/1752609/lorax.log)

**Comment by AdamWill** [comment]
It sounds to me like there may be a DNF bug here we can characterize as "if you are constructing a dnf transaction and there's already something in it that provides `foo`, but you then ask dnf to include `foo` in the transaction, it doesn't recognize that it already has something that provides `foo` and goes looking for another provider of `foo` to add"? Maybe we should try constructing a minimal test case for that.

However, I think for the immediate problem we can just revert https://github.com/rhinstaller/lorax/pull/327 . @bcl just noticed that lorax already explicitly pulls in the corresponding `-logos` package for the provider of `system-release` - see https://github.com/rhinstaller/lorax/blob/master/src/pylorax/treebuilder.py#L112 - and also, anaconda-core explicitly requires system-logos. So we really don't need this. @bcl has just sent https://github.com/rhinstaller/lorax/pull/333 for that.

**Comment by bcl** [comment]
Yeah, next thing is to make a reproducer. There's certainly something wrong with how it handles this. PR #333 should get things working again for now.

**Comment by dustymabe** [comment]
> @bcl just noticed that lorax already explicitly pulls in the corresponding -logos package for the provider of system-release - see https://github.com/rhinstaller/lorax/blob/master/src/pylorax/treebuilder.py#L112

yes, but for some reason that code isn't reached for us. in [kojitask](https://koji.fedoraproject.org/koji/taskinfo?taskID=25243479) we see:

```
DEBUG util.py:439:  could not get the release
```

which means it never added a logos package

> and also, anaconda-core explicitly requires system-logos. So we really don't need this. @bcl has just sent #333 for that.

that's going to change in this (not yet merged) PR: https://github.com/rhinstaller/anaconda/pull/1347

**Comment by AdamWill** [comment]
"yes, but for some reason that code isn't reached for us"

hmm, good catch. wonder why that is.
